[package]
name = "assembly"
version = "0.1.1"
authors = ["Xiphoseer <daniel.g.seiler+lugh"]
edition = "2018"
description = "Rust library for LU tools"
license = "MIT"

[dependencies]
nom = "^4.2"
encoding = "^0.2"
