[package]
name = "assembly-fdb"
version = "0.1.0"
edition = "2018"

[features]
default = ["sqlite", "serde-derives"]
sqlite = ["rusqlite"]
serde-derives = ["serde"]

[dependencies]
hsieh-hash = "0.1"
thiserror = "1.0"
memchr = "2.3"
encoding_rs = "0.8"
derive-new = "0.5"
bytemuck = "1.4"
bytemuck_derive = "1"

[dependencies.assembly-core]
version = "0.3.0"
path = "../core"

[dependencies.rusqlite]
version = "0.21.0"
features = ["bundled"]
optional = true

[dependencies.serde]
version = "1"
optional = true
features = ["derive"]

[dev-dependencies]
prettytable-rs = "0.8"
mapr = "0.8"
structopt = "0.3"
color-eyre = "0.5"
serde_json = "1.0.61"
