[package]
name = "assembly-pack"
version = "0.1.0"
authors = ["Xiphoseer"]
edition = "2018"
homepage = "https://xiphoseer.github.io"
repository = "https://github.com/xiphoseer/assembly_rs"
description = "Packages module for the assembly crate"
license = "MIT"
readme = "README.md"

[dependencies]
assembly-core = { path = "../core", version = "0.1" }
libflate = "0.1"

[dev-dependencies]
getopts = "0.2"
