title: Assembly RS
theme: jekyll-theme-minimal
logo: https://assembly.lu-dev.net/rust-logo-lu.svg
show_downloads: true

keep_files:
  - assembly
  - assembly_core
  - assembly_data
  - assembly_fdb
  - assembly_fdb_raw
  - assembly_maps
  - assembly_pack
  - assembly_sysdiagram
  - assembly_xml
  - src
  - implementors
