title: Assembly RS
theme: jekyll-theme-minimal
logo: https://assembly.lu-dev.net/rust-logo-lu-256.png

keep_files:
  - assembly
  - assembly_core
  - assembly_data
  - assembly_fdb
  - assembly_fdb_raw
  - assembly_maps
  - assembly_pack
  - assembly_sysdiagram
  - assembly_xml
  - src
  - implementors
